[package]
name = "df-bench-nyc-taxi"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]

[dependencies]
datafusion-arrow = "0.1.0-nightly-20180505"
#datafusion = { path = "../../../../../datafusion-rs" }
datafusion = "0.2.11"
flame = "*"
