[package]
name = "generate-wkt"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]

[dependencies]
datafusion-arrow = "0.1.0-nightly-20180406"
datafusion = { path = "../../../../../datafusion-rs" }
